### ISSUE TITLE
Little details

### ISSUE THREAD

**Issue by Israel-Laguan** [wickathou/newsweek-bootstrap#2]
- [x] Maybe change this to be more specific:
![image](https://user-images.githubusercontent.com/36519478/67494505-e57b9e80-f63e-11e9-81ce-a1788eb2ccf6.png)
Try something like this:

```css
ul {
  list-style: none;
}

ul li {
  padding-inline-start: 0;
}
```

- [x] I liked these rules! I did't knew that was posible, thanks for the tip!
![image](https://user-images.githubusercontent.com/36519478/67494655-2ecbee00-f63f-11e9-90af-b7a8234754db.png)

- [x] Maybe try to use more classes instead of select the tags? Is more semantic.
![image](https://user-images.githubusercontent.com/36519478/67494771-65096d80-f63f-11e9-8889-dfd3e03610b0.png)
 
- [x] What about using `css variables` here? 
![image](https://user-images.githubusercontent.com/36519478/67494929-b0bc1700-f63f-11e9-8b19-b906bb36a7d3.png)

**Comment by wickathou** [comment]
Noted, thank you
